# Generated by Django 3.1.5 on 2021-01-21 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Катекория'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Изоброжение'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Катекория'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Изоброжение'),
        ),
    ]
