# Generated by Django 3.1.5 on 2021-01-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210127_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='for_anonymous_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='in_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='sd',
            field=models.BooleanField(default=True, verbose_name='Наличие cd карты'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='sd_vol_max',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Макс.обьем встроенной памяти'),
        ),
    ]
