# Generated by Django 3.1.5 on 2021-01-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210128_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='sd_vol_max',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Макс.обьем встраимовой sd памяти'),
        ),
    ]
