# Generated by Django 3.1.5 on 2021-01-27 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_notebook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook',
            name='url',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='url',
        ),
    ]
